- id: '1651411223240'
  alias: SOMEWHERE Stove Turn on external Fan when Heating
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.SOMEWHERE_stove_pipe_temp
    above: 275
  - platform: numeric_state
    entity_id: sensor.SOMEWHERE_stove_pipe_temp
    below: 200
    condition: []
    action:
    - choose:
      - conditions:
        - condition: numeric_state
          entity_id: sensor.SOMEWHERE_stove_pipe_temp
          above: 225
        sequence:
        - type: turn_on
          entity_id: switch.SOMEWHERE_stove_fan_socket_1
          domain: switch
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.SOMEWHERE_stove_fan_socket_1
      - conditions:
        - condition: numeric_state
          entity_id: sensor.SOMEWHERE_stove_pipe_temp
          below: 275
        sequence:
        - type: turn_off
          entity_id: switch.SOMEWHERE_fan_socket_1
          domain: switch
        - service: switch.turn_off
          data: {}
          target:
            entity_id: switch.house_stove_fan_socket_1
  mode: single
- id: '1669959141194'
  alias: SOMEWHERE Stove HVAC
  description: Set temps and modes on a schedule
  trigger:
  - platform: time
    at: 05:30:00
    alias: '5:30'
  - platform: time
    at: '11:00:00'
    alias: '11:00'
  - platform: time
    at: '23:30:00'
    alias: '23:30'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        before: 06:00:00
        after: 05:30:00
        weekday:
        - sat
        - fri
        - thu
        - wed
        - tue
        - mon
        - sun
        alias: '@5:30'
      - condition: numeric_state
        entity_id: sensor.stove_current_temp_sensor_smoothed
        below: 68
      sequence:
      - alias: Set Temp 71
        service: climate.set_temperature
        data:
          temperature: 71
        target:
          entity_id:
          - climate.SOMEWHERE_wood_pellet_stove
      - alias: 'ECO2 '
        service: select.select_option
        data:
          option: ECO2 - Px then P4
        target:
          entity_id:
          - select.SOMEWHERE_eco_select
      - alias: P4-Low
        service: select.select_option
        data:
          option: P4-Low
        target:
          entity_id:
          - select.SOMEWHERE_power_select
    - conditions:
      - condition: time
        before: '11:30:00'
        weekday:
        - mon
        - tue
        - wed
        - fri
        - thu
        alias: '@11:30'
        after: '11:00:00'
      sequence:
      - alias: 70F
        service: climate.set_temperature
        data:
          temperature: 70
        target:
          entity_id:
          - climate.SOMEWHERE_wood_pellet_stove
      - alias: ECO1
        service: select.select_option
        data:
          option: ECO1 - Heat then OFF
        target:
          entity_id:
          - select.SOMEWHERE_eco_select
      - alias: P4-Low
        service: select.select_option
        data:
          option: P4-Low
        target:
          entity_id:
          - select.SOMEWHERE_power_select
    - conditions:
      - condition: time
        before: '23:59:00'
        weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        after: '23:30:00'
        alias: '23:30'
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 66
        target:
          entity_id: climate.house_wood_pellet_stove
        alias: set 64F
      - alias: ECO1 - Heat then OFF
        service: select.select_option
        data:
          option: ECO1 - Heat then OFF
        target:
          entity_id:
          - select.SOMEWHERE_eco_select
      - service: select.select_option
        data:
          option: P4-Low
        target:
          entity_id:
          - select.SOMEWHERE_power_select
  - service: notify.mobile_app_mircos_iphone
    data:
      message: '5:30/11:00/23:30 Temp change: Currently={{ states(''sensor.SOMEWHERE_stove_current_temp'')}}.
        Set ={{states(''sensor.SOMEWHERE_stove_set_temp'')}}, {{states(''select.SOMEWHERE_eco_select'')}},
        {{states(''select.SOMEWHERE_power_select'')}}'
    enabled: true
  - service: notify.mobile_app_mircos_iphone
    data:
      message: '5:30/11:00/23:30 Temp change: Currently={{ states(''sensor.SOMEWHERE_stove_current_temp'')}}.
        Set ={{states(''sensor.SOMEWHERE_stove_set_temp'')}}, {{states(''select.SOMEWHERE_eco_select'')}},
        {{states(''select.SOMEWHERE_power_select'')}}'
    enabled: false
  mode: single
- id: '1671411223240'
  alias: SOMEWHERE Stove Error Code Display
  description: error code handler
  trigger:
  - platform: numeric_state
    entity_id: sensor.SOMEWHERE_stove_error_code
    above: 0
  condition: []
  action:
  - service: notify.mobile_app_jeffs_iphone_se
    data:
      message: 'Stove Error ={{states(''sensor.SOMEWHERE_stove_current_temp'')}}. Set
        ={{states(''sensor.SOMEWHERE_stove_set_temp'')}}, {{states(''select.SOMEWHERE_stove_eco_select'')}},
        {{states(''select.SOMEWHERE_power_select'')}}, Error: {{states(''sensor.SOMEWHERE_stove_error_code_decoded'')}}'
    enabled: false
  - service: notify.mobile_app_jeffs_128gb_ipad
    data:
      message: 'Stove Error ={{states(''sensor.SOMEWHERE_stove_current_temp'')}}. Set
        ={{states(''sensor.SOMEWHERE_stove_set_temp'')}}, {{states(''select.SOMEWHERE_eco_select'')}},
        {{states(''select.SOMEWHERE_power_select'')}}, Error: {{states(''sensor.SOMEWHERE_stove_error_code_decoded'')}}'
    enabled: false
  mode: single
