- id: '1668144144170'
  alias: House  Pellet stove FIX Goodbye error
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bs_stove_error
    to: 'on'
    enabled: true
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: numeric_state
    entity_id: sensor.esph_house_stove_pipe_temp
    below: 101
  - platform: numeric_state
    entity_id: sensor.esph_house_stove_current_temp
    alias: Add TEMPLATE set temp - 4 < current temp
    below: 65
    enabled: false
  condition:
  - condition: state
    entity_id: binary_sensor.bs_stove_error
    state: 'on'
    alias: Confirm Binary Sensor Stove Error - > Current temp is 4 deg < Set Temp
  - condition: state
    entity_id: climate.house_wood_pellet_stove
    attribute: hvac_action
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.esph_house_stove_pipe_temp
    below: 101
  - condition: numeric_state
    entity_id: sensor.esph_house_stove_set_temp
    above: 60
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id: climate.house_wood_pellet_stove
  - service: notify.mobile_app_jeffs_128gb_ipad
    data:
      message: Goodbye! fixed, Currently={{ states('sensor.esph_house_stove_current_temp')}}.
        Set  temp={{states('sensor.esph_house_stove_set_temp')}}
  - service: notify.mobile_app_jeffs_iphone_se
    data:
      message: Goodbye! fixed, Currently={{ states('sensor.esph_house_stove_current_temp')}}.
        Set temp={{states('sensor.esph_house_stove_set_temp')}}
  - service: logbook.log
    data:
      name: Stove error
      message: .  Current temp ={{ states('sensor.esph_house_stove_current_temp')}}F.  -
        set temp={{states('sensor.esph_house_stove_set_temp')|float(0) }}
  mode: single
- id: '1668625754729'
  alias: House Pellet Stove Turn on Fan when Heating
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.esph_house_stove_pipe_temp
    above: 225
  - platform: numeric_state
    entity_id: sensor.esph_house_stove_pipe_temp
    below: 125
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.esph_house_stove_pipe_temp
        above: 225
      sequence:
      - type: turn_on
        device_id: 53a14c12b9ec2a366c41befbb0691f9b
        entity_id: switch.house_stove_fan_socket_1
        domain: switch
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.house_stove_fan_socket_1
    - conditions:
      - condition: numeric_state
        entity_id: sensor.esph_house_stove_pipe_temp
        below: 275
      sequence:
      - type: turn_off
        device_id: 53a14c12b9ec2a366c41befbb0691f9b
        entity_id: switch.house_stove_fan_socket_1
        domain: switch
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.house_stove_fan_socket_1
  mode: single
- id: '1668692171523'
  alias: House Pellet stove error code handler
  description: Turn stove off then on if error code happens
  trigger:
  - platform: numeric_state
    entity_id: sensor.esph_house_stove_error_code
    above: 0
    alias: Error code above 0
  condition: []
  action:
  - type: turn_off
    device_id: 53a14c12b9ec2a366c41befbb0691f9b
    entity_id: switch.mini_smart_plug_6_socket_1
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_on
    device_id: 53a14c12b9ec2a366c41befbb0691f9b
    entity_id: switch.mini_smart_plug_6_socket_1
    domain: switch
  - service: notify.mobile_app_jeffs_iphone_se
    data:
      message: 'Stove Error Currently={{states(''sensor.esph_house_stove_current_temp'')}}.
        Set ={{states(''sensor.esph_house_stove_set_temp'')}}, {{states(''select.esph_house_eco_select'')}},
        {{states(''select.esph_house_power_select'')}}, Error: {{states(''sensor.esph_house_error_code_decoded'')}}'
  - service: notify.mobile_app_jeffs_128gb_ipad
    data:
      message: 'Stove Error Currently={{states(''sensor.esph_house_stove_current_temp'')}}.
        Set ={{states(''sensor.esph_house_stove_set_temp'')}}, {{states(''select.esph_house_eco_select'')}},
        {{states(''select.esph_house_power_select'')}}, Error: {{states(''sensor.esph_house_error_code_decoded'')}}'
  mode: single
- id: '1669120904931'
  alias: 'House Pellet stove OVER TEMP PROTECTION '
  description: ''
  trigger:
  - platform: template
    value_template: "        {{ float( states('sensor.stove_current_temp_sensor_smoothed')
      , 0)\n          >=  float( states('sensor.esph_house_stove_set_temp') , 0) +2
      }}"
  condition:
  - condition: template
    value_template: "        {{ float( states('sensor.stove_current_temp_sensor_smoothed')
      , 0)\n          >=  float( states('sensor.esph_house_stove_set_temp') , 0) +2
      }}"
    alias: 'Current temp smoothed  >= Set temp +2 '
  - condition: or
    conditions:
    - condition: state
      entity_id: climate.house_wood_pellet_stove
      attribute: hvac_action
      state: heating
    - condition: state
      entity_id: climate.house_wood_pellet_stove
      attribute: hvac_action
      state: idle
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.house_wood_pellet_stove
    alias: Climate HVAC to OFF
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  mode: queued
  max: 10
- id: '1669959141194'
  alias: House Pellet stove HVAC 5:30 & 11am
  description: ''
  trigger:
  - platform: time
    at: 05:30:00
    alias: 5:30am
  - platform: time
    at: '11:00:00'
    alias: 11:00am
  - platform: time
    at: '23:30:00'
    alias: 11:30pm
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        before: 06:00:00
        after: 05:30:00
        weekday:
        - sat
        - fri
        - thu
        - wed
        - tue
        - mon
        - sun
        alias: '@5:30am'
      - condition: numeric_state
        entity_id: sensor.stove_current_temp_sensor_smoothed
        below: 68
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 71
        target:
          entity_id: climate.house_wood_pellet_stove
        alias: Set Temp 71
      - service: select.select_option
        data:
          option: ECO2 - Px then P4
        target:
          entity_id: select.esph_house_eco_select
        alias: 'ECO2 '
      - service: select.select_option
        data:
          option: P1-High
        target:
          entity_id: select.esph_house_power_select
        alias: P1-High
    - conditions:
      - condition: time
        before: '11:30:00'
        weekday:
        - mon
        - tue
        - wed
        - fri
        - thu
        alias: '@11:30am'
        after: '11:00:00'
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 62
        target:
          entity_id: climate.house_wood_pellet_stove
        alias: Set 62
      - service: select.select_option
        data:
          option: ECO1 - Heat then OFF
        target:
          entity_id: select.esph_house_eco_select
        alias: ECO1
      - service: select.select_option
        data:
          option: P4-Low
        target:
          entity_id: select.esph_house_power_select
        alias: P4-Low
    - conditions:
      - condition: time
        before: '23:59:00'
        weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        after: '23:30:00'
        alias: 11:30pm
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 64
        target:
          entity_id: climate.house_wood_pellet_stove
        alias: set 64F
      - service: select.select_option
        data:
          option: ECO1 - Heat then OFF
        target:
          entity_id: select.esph_house_eco_select
        alias: ECO1 - Heat then OFF
      - service: select.select_option
        data:
          option: P4-Low
        target:
          entity_id: select.esph_house_power_select
  - service: notify.mobile_app_jeffs_iphone_se
    data:
      message: '5:30am & 11am Temp change: Currently={{ states(''sensor.esph_house_stove_current_temp'')}}.
        Set ={{states(''sensor.esph_house_stove_set_temp'')}}, {{states(''select.esph_house_eco_select'')}},
        {{states(''select.esph_house_power_select'')}}'
  - service: notify.mobile_app_jeffs_128gb_ipad
    data:
      message: '5:30am & 11am Temp change: Currently={{ states(''sensor.esph_house_stove_current_temp'')}}.
        Set ={{states(''sensor.esph_house_stove_set_temp'')}}, {{states(''select.esph_house_eco_select'')}},
        {{states(''select.esph_house_power_select'')}}'
  mode: single